USE ProyectoDB;
--
-- Triggers
--
DELIMITER //

CREATE OR REPLACE TRIGGER descuento_universidad BEFORE INSERT ON PROGRAMA
FOR EACH ROW

BEGIN
	IF NEW.ID_INSTIT < 2 THEN SET NEW.COSTO = NEW.COSTO*0.9;

	END IF;
END //

DELIMITER ;

--Prodcedimiento 

DELIMITER |
CREATE OR REPLACE PROCEDURE num_users (OUT numero INT)
BEGIN
	SELECT COUNT(*) INTO numero FROM DOCENTE
	WHERE DOCENTE.NOMBRE_USUARIO IS NOT NULL;
END |
DELIMITER ;

CALL num_users(@a);

SELECT @a;
